name: CI

on:
  push:
  pull_request:

jobs:
  test-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testName:
          - 'check-your-website'
          - 'crtsh'
          - 'cryptcheck'
          - 'ssllabs'
          - 'hstspreload'
          - 'httpobservatory'
          - 'lighthouse'
          - 'psi'
          - 'securityheaders'
          - 'webbkoll'
          - 'webhint'
          - 'yellowlab'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --silent
      - name: Run test with name ${{ matrix.testName }}
        run: yarn test:${{ matrix.testName }}
        continue-on-error: false
  