name: CI

on:
  push:
  pull_request:

jobs:
  test-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - name: Install dependencies
        run: yarn --silent
      - name: Run tests
        run: yarn test:${{ matrix.testName }}
        continue-on-error: false
        
  check-your-website:
    strategy:
      matrix:
        testName: 'check-your-website'
  crtsh:
    strategy:
      matrix:
        testName: 'crtsh'
  cryptcheck:
    strategy:
      matrix:
        testName: 'cryptcheck'
  ssllabs:
    strategy:
      matrix:
        testName: 'ssllabs'
  hstspreload:
    strategy:
      matrix:
        testName: 'hstspreload'
  httpobservatory:
    strategy:
      matrix:
        testName: 'httpobservatory'
  lighthouse:
    strategy:
      matrix:
        testName: 'lighthouse'
  psi:
    strategy:
      matrix:
        testName: 'psi'
  securityheaders:
    strategy:
      matrix:
        testName: 'securityheaders'
  webbkoll:
    strategy:
      matrix:
        testName: 'webbkoll'
  webhint:
    strategy:
      matrix:
        testName: 'webhint'
  yellowlab:
    strategy:
      matrix:
        testName: 'yellowlab'